### ISSUE TITLE
Dropping v0.5?

### ISSUE THREAD

**Issue by cormullion** [JuliaAstro/AstroLib.jl#1]
Just wondering why 0.5 is not supported? I don't think v0.6 is usable yet...

**Comment by giordano** [comment]
It isn't my intention to release a new version for Julia 0.6 only before 0.6 is out.

However, probably I'll tag a new version for Julia 0.4 and 0.5 including fixes I applied after AstroLib 0.0.6.

**Comment by cormullion** [comment]
Ah, OK, the readme.md is just waiting for a few months to become valid? A bit confusing in the meantime, though... :)

**Comment by giordano** [comment]
Well, the README is in sync with the rest of the repository ;-)  But yes, that may be confusing for people coming and reading that.  In addition, I should specify that older versions are anyway available for Julia 0.4 and 0.5.  Thanks for reminding me!

**Comment by giordano** [comment]
Version 0.0.7 tagged, `README.md` updated to explain that older versions run on Julia 0.4 and 0.5.  Thank you!
