### ISSUE TITLE
Equation of time?

### ISSUE THREAD

**Issue by cormullion** [JuliaAstro/AstroLib.jl#12]
Is it possible to calculate the equation of time using existing functions in AstroLib?

Also, is it a good time to tag another release — I'm still picking up January's 0.0.7?

**Comment by giordano** [comment]
> Is it possible to calculate the equation of time using existing functions in AstroLib?

I'm not very familiar with it.  There are [`sunpos`](https://juliaastro.github.io/AstroLib.jl/latest/ref.html#AstroLib.sunpos-Tuple{Real}), which gives the right ascension of the Sun, and [`kepler_solver`](https://juliaastro.github.io/AstroLib.jl/latest/ref.html#AstroLib.kepler_solver-Tuple{Real,Real}) to solve the Kepler equation, I don't know if they suffice to calculate the equation of time.

> Also, is it a good time to tag another release — I'm still picking up January's 0.0.7?

I was waiting for Julia 0.6 to be released, before rolling a new AstroLib.jl version, but Julia 0.6 is taking more time than expected.  There have not been many changes to the library since last release: https://github.com/JuliaAstro/AstroLib.jl/compare/f1dea9a...8b47302, the only additions are `ordinal`, `tics`, `tic_one`, `ticpos`.  The largest change was to the documentation ;-)

**Comment by cormullion** [comment]
And `precompile()`, judging by the delay when loading... :)

I'll see if `sunpos` can help.

**Comment by cormullion** [comment]
Just got back to this now you've released again. In case anyone else searches, I managed to convince myself that it's easy to get the Eq of Time from AstroLib:

```
function equationoftime(dt::DateTime)
    # Greenwich Sidereal Time in hours:
    longitude = 0
    GAST = ct2lst(longitude, jdcnv(dt))

    # UTC since midnight in hours:
    timesincemidnight = (jdcnv(dt) - jdcnv(round(dt, Dates.Day, RoundDown))) * 24

    # sun's Right Ascension in hours:
    α = (sunpos(jdcnv(dt), radians=true)[1]/2pi) * 24

    # Eq of Time in minutes:
    eot = (GAST - α - timesincemidnight + 12) * 60

    # compensate for some odd wrapping round the 24h mark????????
    if eot > 60
        eot -= 1440 # minutes in day
    end
    return eot
end
```

**Comment by giordano** [comment]
Nice!  Would you submit this function for inclusion in AstroLib? :-)

**Comment by cormullion** [comment]
Love to but I'd be happier if I could first work out why it suddenly needs 1440 minutes added. 😀Presumably something earlier on needs a `mod2pi`.

**Comment by giordano** [comment]
Ok.  BTW, I'm more and more persuaded by removing `cirrange`.  It's equivalent to `mod`, for modulo 2pi, `mod2pi` is more accurate (but a bit slower).

**Comment by giordano** [comment]
@cormullion can you please give us a reference about how to compute the equation of time?  And an input value for when you wrap the value.

**Comment by cormullion** [comment]
I'll have a look tomorrow. I quite like [Duffett-Smith's book](https://archive.org/stream/Practical_Astronomy_with_your_Calculator_or_Spreadsheet_4th_edition_by_Peter_Duf/Practical_Astronomy_with_your_Calculator_or_Spreadsheet_4th_edition_by_Peter_Duffett-Smith_Jonathan_Zwart#page/n139/mode/2up). Meeus uses a different formula.

**Comment by giordano** [comment]
Uhm
```julia
julia> equationoftime(DateTime(2010, 7, 27, 12))
-6.539878295300348
```
that is -6m 32s (you can use `sixty` to get the sexagesimal representation), with the opposite sign compared to what is written in the book.  The right ascension of the Sun is also slightly different (`sunpos(jdcnv(DateTime(2010, 7, 27,12)))[1] / 15 = 8.446295077037009`; BTW, I believe this is better than using radians and then converting back to decimal hours ;-), but maybe the algorithm is different.

**Comment by cormullion** [comment]
I think the sign is a convention (e.g. on sundials you might see "sun faster" or "sun slower"). The version of the Meeus algorithm I coded in Astro.jl (for Julia version 0.3 so I was a real beginner!) is:

```
function equation_time(jd)
    tau = jd_to_jcent(jd)/10
    _p = [280.4664567, 360007.6982779, 0.03032028, 1/49931, -1/15300, -1/2000000]
    L0 = mod2pi(deg2rad(polynomial(_p, tau)))
    (L, B, R)  = sun_dimension3(jd)
    (L, B)     = vsop_to_fk5(jd, L, B)
    deltaPsi   = nut_in_lon(jd)
    epsilon    = true_obliquity(jd)
    asc,decl   = ecl_to_equ(L, B, epsilon)
    eqt = L0 - deg2rad(0.0057183) - asc + deltaPsi * cos(epsilon)
    if eqt > pi/2
        eqt = -((2 * pi) - eqt)
    end
    return eqt/(2 * pi) * 1440
end
```

Running the two algorithms and graphing them gives pretty similar results:

![screen shot 2017-05-09 at 10 31 28](https://cloud.githubusercontent.com/assets/52289/25844761/719e9440-34a3-11e7-8c26-3928996ee4ca.png)

Given the uses for the Equation I think it's close enough. (I'm no scientist! :))

Will look into the mod2pi rounding sometime.
