### ISSUE TITLE
Use Documenter.jl

### ISSUE THREAD

**Issue by giordano** [JuliaAstro/AstroLib.jl#2]
Currently, the documentation is in reStructuredText, the Markdown docstrings are extracted with an Emacs Lisp script and then converted to rst with pandoc.  However, nowadays [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) is available and it should make it simple to handle documentation largely based on docstrings and AstroLib should use it.

**Comment by cormullion** [comment]
I might have a go at this next week. I've just finished making a Documenter.jl documentation for Luxor.jl, so I might still remember how I got it working...

**Comment by kbarbary** [comment]
:+1:  It would be nice to do this for FITSIO too (I think the only other JuliaAstro repo with significant documentation).

**Comment by giordano** [comment]
@kbarbary I don't have access to the settings page of the repository.  It's needed to [install the SSH key](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#SSH-Deploy-Keys-1).  Can you please do that?

**Comment by kbarbary** [comment]
@giordano You should now have admin rights to all JuliaAstro repos.

**Comment by giordano** [comment]
Thank you @kbarbary!  New documentation is available at http://juliaastro.github.io/AstroLib.jl/latest/intro.html

Thank you so much to @cormullion for the great help and the logo!

**Comment by cormullion** [comment]
Yay, it's all working! Good job, the integration stage is a little tricky, isn't it?

About the FITSIO DOCS: (cc @kbarbary) Unlike AstroLib, which already had all the docstrings in place, it looks like FITSIO source files would need extensive editing to add docstrings in Markdown format. Being unfamiliar with the code, I'd be reluctant to tackle that part of it. But I'll help out in other ways if possible.

**Comment by giordano** [comment]
> Yay, it's all working! Good job, the integration stage is a little tricky, isn't it?

Yep, it takes a while to setup everything and grasp the details of what you're doing, but after that everything goes smoothly.  For documentations largely based on docstrings Documenter is a great tool.

While I still find that reStructuredText is superior to Markdown in terms of capabilities (but Markdown is much easier as language), I'm pretty happy with the result with Documenter.
