### ISSUE TITLE
Regarding a slight change in the mean obliquity

### ISSUE THREAD

**Issue by TestSubjector** [JuliaAstro/AstroLib.jl#24]
Putting this here for discussion. 

The routines co_nutate and co_aberration use the formula `eps0 = @evalpoly t 84381.448 -46.815 -0.00059 0.001813` to find out mean obliquity. However [according to Wikipedia](https://en.wikipedia.org/wiki/Axial_tilt#Short_term), this formula has been updated in the Astronomical Almanac, 2010. So should we use the latter here? Note that I haven't verified the citation as I don't have access to the almanac.

One reason against doing this could be because it appears to clash with the equation mentioned in this [report](https://ipnpr.jpl.nasa.gov/progress_report/42-196/196C.pdf)(Pg 11).

**Comment by giordano** [comment]
Good spot!  Astropy uses the new definition by default: https://github.com/astropy/astropy/blob/326ac866edac04e77fec842eae7ded01eb28a7a8/astropy/coordinates/earth_orientation.py#L109  The coefficients look the same as those in Wikipedia

If the obliquity is to be computed in more than one place, we might define a function to calculate it at the given time, to reduce duplication of code and enforce consistency (which often lacks in IDL AstroLib).

**Comment by TestSubjector** [comment]
> If the obliquity is to be computed in more than one place, we might define a function to calculate it

I was thinking along the same lines. A function that takes in Julian date and returns the obliquity of the ecliptic. I'll work on this.

**Comment by TestSubjector** [comment]
The obliquity function that uses the newer formula to calculate mean obliquity(and then true obliquity) has been added to the library by PR #25. Closing issue.
