### ISSUE TITLE
Is AstroLib precompiled?

### ISSUE THREAD

**Issue by cormullion** [JuliaAstro/AstroLib.jl#5]
I noticed that there's no entry for `AstroLib` in my `/Users/me/.julia/lib/v0.5/`. Is the library pre-compilable? I noticed a rather relaxed 5 second startup time...

**Comment by giordano** [comment]
It should be precompiled: https://github.com/JuliaAstro/AstroLib.jl/blob/13efeb9753924f0c940ff50800daf592f243acd1/src/AstroLib.jl#L4

**Comment by cormullion** [comment]
`__precompile__()`?

**Comment by giordano** [comment]
oops, thank you!
