### ISSUE TITLE
Documentation up to date?

### ISSUE THREAD

**Issue by cormullion** [JuliaAstro/AstroLib.jl#52]
Not sure, are the docs building on the gh-pages branch?

**Comment by giordano** [comment]
I don't think so :confused:

**Comment by giordano** [comment]
Oops https://github.com/JuliaAstro/AstroLib.jl/blob/master/docs/make.jl

**Comment by cormullion** [comment]
I bet that was my fault... :)

**Comment by giordano** [comment]
Updated documentation is now live for `latest`: http://juliaastro.github.io/AstroLib.jl/latest/ :tada: 

Thank for pointing this out!
