### ISSUE TITLE
Errors running on 1.1

### ISSUE THREAD

**Issue by cormullion** [JuliaAstro/AstroLib.jl#54]
https://github.com/JuliaLang/julia/issues/30374

**Comment by giordano** [comment]
I saw that, but today I won't probably have the time to have a look at the issue. Thanks for opening the ticket!

**Comment by benelsen** [comment]
Almost certainly a bug upstream in StaticArrays: https://github.com/JuliaLang/julia/issues/30374#issuecomment-447076786 & https://github.com/JuliaArrays/StaticArrays.jl/pull/568
