### ISSUE TITLE
can not access "https://www.ngdc.noaa.gov/geomag/data/poles/NP.xy"

### ISSUE THREAD

**Issue by yangcht** [JuliaAstro/AstroLib.jl#6]
LoadError: failed process: Process(`curl -o NP.xy -L https://www.ngdc.noaa.gov/geomag/data/poles/NP.xy`, ProcessExited(6)) [6]

The link seems broken.... thus I can not build the Lib... 

Could you kindly fix this?

**Comment by giordano** [comment]
I'll look into it, but please note that you can use the package anyway, only a couple of functions need that file. You should only get a warning when loading the package.

**Comment by giordano** [comment]
I can download the file now, can you please confirm?

**Comment by yangcht** [comment]
I am still having trouble accessing the url. It seems that I can not resolve the DNS. Then I tried with ip directly. I got 403 error says:
"You don't have permission to access /geomag/data/poles/NP.xy on this server."

**Comment by giordano** [comment]
What if you remove the `s` from the protocol? http://www.ngdc.noaa.gov/geomag/data/poles/NP.xy

I could upload the file to another server (like bintray), but I prefer to use to the original file provided by NOAA (maybe as a fallback solution?).

**Comment by yangcht** [comment]
I can access it using a proxy in the US. I think the website has banned the access from China (including Hong Kong).

**Comment by giordano** [comment]
Oh, I suspected that there was a firewall involved, indeed it's a big one.

Do you think that uploading the file to another server would be useful?  If so, can you please tell me if you can download https://bintray.com/giordano/Cuba-Shared-Library/download_file?file_path=libcuba-v4.2-20150925-x86_64.dll ?  Just to know if you can access this site.

**Comment by yangcht** [comment]
Yes, it would be helpful.  This url is accessible from Hong Kong at least, though it's still banned by the Chinese Great Firewall.

**Comment by giordano** [comment]
Uhm, I'm not sure it's worth doing so if the whole China is blocked anyway.

**Comment by yangcht** [comment]
It's quite unstable. I did a test. Some places in China can access it while some can not... But for the NOAA URL, some of my friends in Germany said they can not access it either...

**Comment by giordano** [comment]
I uploaded a copy of the file to bintray, which will be retrieved by users upon building the package.  I also added a more descriptive warning in case download fails again.  I hope it will work for you.

**Comment by tkelman** [comment]
may want to backport just that commit to a branch of of 0.0.7, and make an 0.0.8 release that still supports julia 0.4 and 0.5? the old download started failing on pkgeval http://pkg.julialang.org/detail/AstroLib.html which runs on a machine at MIT that doesn't usually have any firewall problems
