### ISSUE TITLE
Could not find file NP.xy

### ISSUE THREAD

**Issue by pduenas** [JuliaAstro/AstroLib.jl#69]
Hi, I've added the AstroLib package recently and noticed that the NP.xy library is not in the same URL as indicated in the current build.jl file. The new URL is: https://www.ngdc.noaa.gov/geomag/data/poles/NP.xy
I've also noticed that need to be "located" in the US to be able to download it. (Thanks VPN connection :))

**Comment by giordano** [comment]
Should be already fixed by #67. I guess I need to do a release which includes that change

**Comment by giordano** [comment]
[`v0.4.1`](https://github.com/JuliaAstro/AstroLib.jl/releases/tag/v0.4.1) is now available and it includes #67.
