### ISSUE TITLE
Why does sunpos accept both scalars AND vectors?

### ISSUE THREAD

**Issue by yakir12** [JuliaAstro/AstroLib.jl#72]
Unless there is a real reason for `sunpos` to accept vectors, I suggest removing the implementation in https://github.com/JuliaAstro/AstroLib.jl/blob/54933951f669b2e47bcd4f64f27cfe0ad90b60e0/src/sunpos.jl#L139.

**Comment by giordano** [comment]
Because it returns a tuple of vectors
