### ISSUE TITLE
Confusing double-meaning of the word "altitude"

### ISSUE THREAD

**Issue by yakir12** [JuliaAstro/AstroLib.jl#80]
The word "altitude" is used for denoting an elevation angle (e.g. [here](https://github.com/JuliaAstro/AstroLib.jl/blob/54933951f669b2e47bcd4f64f27cfe0ad90b60e0/src/altaz2hadec.jl#L40)) AND height from sea-level (e.g. [here](https://github.com/JuliaAstro/AstroLib.jl/blob/54933951f669b2e47bcd4f64f27cfe0ad90b60e0/src/geo2eci.jl#L38)). This is confusing. I'm not sure what the best way to solve this is. Are there any agreed upon conventions? If it's impossible to agree on some standard, maybe include a note about it in the doc-strings?

**Comment by giordano** [comment]
I mean, the convention is precisely to call both of them "altitude". And the docstrings you linked (mostly borrowed from the upstream AstroLib package) already elaborate on what "altitude" they refer to.

**Comment by yakir12** [comment]
Thanks for the rapid response!

> I mean, the convention is precisely to call both of them "altitude". 

Frustrating.. 

> And the docstrings you linked (mostly borrowed from the upstream AstroLib package) already elaborate on what "altitude" they refer to.

I agree. OK, closing this then.
